[build]
  base = "im-web"
  command = "npm run dev"
  publish = "dist"

  # 构建时使用的环境变量
  [build.environment]
    VUE_APP_SERVER_URL="https://back.hs.airoe.cn"
    VUE_APP_TURNSTILE_SITE_KEY="0x4AAAAAACmJCFDcKhJ4p3Ua"

# 支持 HTML5 History 路由（SPA）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false